services:
    manatwork.multicolumnwizard.build-data-definition:
        class: MenAtWork\MultiColumnWizard\DcGeneral\UpdateDataDefinition
        tags:
            -   name: kernel.event_listener
                event: dc-general.factory.build-data-definition
                method: addMcwFields
                priority: -5000
