services:
  manatwork.multicolumnwizard.build-data-definition:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\DcGeneral\UpdateDataDefinition
    tags:
      - name: kernel.event_listener
        event: dc-general.factory.build-data-definition
        method: addMcwFields
        priority: -5000

  manatwork.multicolumnwizard.build-tiny-mce:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\TinyMce
    tags:
      - name: kernel.event_listener
        event: men-at-work.multi-column-wizard.get-tiny-mce
        method: executeEvent
