services:
  menatwork.multicolumnwizard.events_listener.build-data-definition:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\DcGeneral\UpdateDataDefinition
    tags:
      - name: kernel.event_listener
        event: dc-general.factory.build-data-definition
        method: addMcwFields
        priority: -5000

  menatwork.multicolumnwizard.events_listener.build-tiny-mce:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\TinyMce
    tags:
      - name: kernel.event_listener
        event: men-at-work.multi-column-wizard-bundle.get-tiny-mce
        method: executeEvent

  menatwork.multicolumnwizard.events_listener.build-date-picker:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\DatePicker
    tags:
      - name: kernel.event_listener
        event: men-at-work.multi-column-wizard-bundle.get-date-picker
        method: executeEvent

  menatwork.multicolumnwizard.events_listener.create-widget:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\CreateWidget
    tags:
      - name: kernel.event_listener
        event: men-at-work.multi-column-wizard-bundle.create-widget
        method: createWidgetContao
      - name: kernel.event_listener
        event: men-at-work.multi-column-wizard-bundle.create-widget
        method: createWidgetDcGeneral
