services:
  menatwork.multicolumnwizard.events_listener.execute_post_actions:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ExecutePostActions
    arguments:
      - '@event_dispatcher'

  menatwork.multicolumnwizard.events_listener.initialize_system:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem

  menatwork.multicolumnwizard.events_listener.load_data_container:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\LoadDataContainer

  menatwork.multicolumnwizard.events_listener.parse_template:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ParseTemplate
