services:
  menatwork.multicolumnwizard-bundle.events_listener.execute_post_actions:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ExecutePostActions
    public: true
    arguments:
      - '@event_dispatcher'

  menatwork.multicolumnwizard-bundle.events_listener.initialize_system:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem
    public: true

  menatwork.multicolumnwizard-bundle.events_listener.load_data_container:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\LoadDataContainer
    public: true

  menatwork.multicolumnwizard-bundle.events_listener.parse_template:
    class: MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ParseTemplate
    public: true
