services:
  maw.mcw.events.listener.execute_post_actions:
    class: MenAtWork\MultiColumnWizardBundle\Contao\Events\ExecutePostActions

  maw.mcw.events.listener.initialize_system:
    class: MenAtWork\MultiColumnWizardBundle\Contao\Events\InitializeSystem

  maw.mcw.events.listener.load_data_container:
    class: MenAtWork\MultiColumnWizardBundle\Contao\Events\LoadDataContainer

  maw.mcw.events.listener.parse_template:
    class: MenAtWork\MultiColumnWizardBundle\Contao\Events\ParseTemplate
